### ISSUE TITLE
【Bug】getBaWangCanList函数好像不好使了，显示列表不存在了，我运行的时候总是弹出来一个登录窗口，扫码之后也不管用，大佬有时间看一下

### ISSUE THREAD

**Issue by bby2729** [zhangjinbao520/BaWangCan#3]

**Comment by ZhangJinbao520** [comment]
本地未复现，再咨询一下~
代码版本：是什么？——1月？2月？
库版本：Python 3.9 OR 2.7？——python -m pip list
OS：是什么？——Windows？
操作：是什么？——选择城市列表，开始运行之后出现的吗？
出现问题状态：是什么？——是脚本运行，还是封包exe运行了
PS：之前有一个版本，登录窗口和运行窗口切换有问题【已解决】。

**Comment by bby2729** [comment]
ui脚本使用后，停留在扫描登陆二维码的界面，扫描登陆后没有其他变化，
使用的是python3.6，Windows，可能是您提到的登录窗口和运行窗口切换的问题，src2也遇到了同样的问题

**Comment by bby2729** [comment]
使用了更新的代码，问题已解决，非常感谢
